### ISSUE TITLE
CORS error on load

### ISSUE THREAD

**Issue by lorddusk** [friendsoftheheron/pwa#1]
After inserting my login details, and clicking on LABS, it's giving me several errors in the console.

Amongst them is this CORS error:

Access to fetch at 'https://heron.alwaysdata.net/data.json' from origin 'https://friendsoftheheron.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Edit: A few lines further I'm getting this error too:

sw.js:79 sw:fetch:https://heron.alwaysdata.net/data.json TypeError: Failed to fetch
    at sw.js:65:27

Full console log screenshot:
![image](https://github.com/friendsoftheheron/pwa/assets/425207/a75f760d-9e40-4f13-981d-d85a42893c83)

**Comment by friendsoftheheron** [comment]
It's even worse: The whole backend seems to be broken.
We'll look in to it.

**Comment by friendsoftheheron** [comment]
Backend functionality has been restored.

**Comment by Yannick-XY** [comment]
I think it's still broken...?

In chrome i get the above seen CORS errors, after starting chrome in unsafe mode always 500-Server Errors are responded.
Tried from https://friendsoftheheron.github.io/pwa/ and https://heron.alwaysdata.net and also on android app but always getting the same errors.
