### ISSUE TITLE
No possibility to enter answers

### ISSUE THREAD

**Issue by Pietertje54** [friendsoftheheron/pwa#4]
As os september 14 I'm no longer able to enter solutions/answers to questions in the ALCs. I can open the location, read all the information but it's not possible to enter the solution bar nor to press the enter button. I have reinstalled the app but with the same result...

Anyone else with this problem? And how did you solve it?

**Comment by friendsoftheheron** [comment]
There was a bug in v0.5.7.4, causing the problem you mention. This bug has been fixed in v0.5.7.4.1 a day later. Do you still encounter this problem?

**Comment by Pietertje54** [comment]
No, as far as I'm concerned the problem is solved 👍..

Op do 26 sep. 2024 18:11 schreef Friends of the Heron <
***@***.***>:
