### ISSUE TITLE
No owl

### ISSUE THREAD

**Issue by muisje19** [friendsoftheheron/pwa#7]
I say:

used to log my adventures with this program. First week no problems, but now my owl has gone. Friend with same version, same problem

Your answer 

Your trial period has ended. The owl returns when you enter the correct answer for a lab where there is no answer yet. Or you can buy the owl (and other birds) in the donate section.

I say: 
Nobody knows about a trial and everybody thinks its a free prog and the donate part is volunteer

**Comment by friendsoftheheron** [comment]
If you don't like it: Don't use it.

As stated in the about section:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
