### ISSUE TITLE
No Login with my Main Account?

### ISSUE THREAD

**Issue by DaRue86KrissyDD** [friendsoftheheron/pwa#8]
Hello, I have a problem logging in to my main account. I'm sure it's maybe the same problem as registering on this platform. Because here I have to leave out the special character "_" so that I can register. That will be sure that the problem is with PWA. Because there I can see questions in the area, but a "log" doesn't work. If I accept my sock puppet account there, without special characters, everything works fine and the log works. 

So 
This 1 is due to the special characters, e.g. "_" and / or 
Theses 2
The nickname is too long overall. (17 letters)

**Comment by friendsoftheheron** [comment]
For some reason you managed to get in our database with both the username with and without underscores. You username without underscores have been removed.
The backend has been updated to prevent this kind of problems in the future.
You can use nicknames with special characters and longer than 17 characters.

**Comment by DaRue86KrissyDD** [comment]
I just changed my username back to an underscore on Geocaching and it still doesn't work. The log switch has no solution and no function. The same account without an underscore (changed name) now also has no function.

Von meinem iPhone 15 gesendet

> Am 30.10.2024 um 23:44 schrieb Friends of the Heron ***@***.***>:
> 
> For some reason you managed to get in our database with both the username with and without underscores. You username without underscores have been removed.
> The backend has been updated to prevent this kind of problems in the future.
> You can use nicknames with special characters and longer than 17 characters.

**Comment by friendsoftheheron** [comment]
Converted some credits to owl and eagle. Think this is what you want.

**Comment by DaRue86KrissyDD** [comment]
Thank you. Now is it Perfect.


> Am 31.10.2024 um 22:12 schrieb Friends of the Heron ***@***.***>:
> 
> Converted some credits to owl and eagle. Think this is what you want.
