### ISSUE TITLE
All Adventure Lab are in red

### ISSUE THREAD

**Issue by davetarget** [friendsoftheheron/pwa#9]
On my account all AL are in red. 
And is not possible to log. 
My uderid is: davetarget_team

**Comment by friendsoftheheron** [comment]
Cannot see anything wrong with that account.
Is is really red `#90040B` or orange `#f15927` or yellow `#E98300`?
If it's yellow, You've unchecked "Hide logged" and you already logged labs are shown. You cannot re-log the labs you've already logged.

**Comment by davetarget** [comment]
Hello,

I think it's orange.
I'm logged in, and when I log in with my partner's account, it works.
Can you help me?
***@***.***

De : Friends of the Heron ***@***.***>
Envoyé : jeudi 31 octobre 2024 22:25
À : friendsoftheheron/pwa ***@***.***>
Cc : davetarget ***@***.***>; Author ***@***.***>
Objet : Re: [friendsoftheheron/pwa] All Adventure Lab are in red (Issue #9)


Cannot see anything wrong with that account.
Is is really red #90040B or orange #f15927 or yellow #E98300?
If it's yellow, You've unchecked "Hide logged" and you already logged labs are shown. You cannot re-log the labs you've already logged.

-

**Comment by friendsoftheheron** [comment]
You need to login to get the extra features
